# Generated by Django 6.0.3 on 2026-03-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название услуги"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Например: bi-star, bi-heart",
                        max_length=100,
                        verbose_name="Иконка (Bootstrap icon class)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги ресторана",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Уникальный идентификатор (например: about_text, main_banner)",
                        max_length=100,
                        unique=True,
                        verbose_name="Ключ",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Описание контента для админки",
                        max_length=200,
                        verbose_name="Название",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("image", "Изображение"),
                            ("html", "HTML"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Тип контента",
                    ),
                ),
                (
                    "text_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="Текстовое значение"
                    ),
                ),
                (
                    "image_value",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="content/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Элемент контента",
                "verbose_name_plural": "Контент сайта",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("chef", "Шеф-повар"),
                            ("cook", "Повар"),
                            ("manager", "Менеджер"),
                            ("waiter", "Официант"),
                            ("bartender", "Бармен"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Должность",
                    ),
                ),
                ("photo", models.ImageField(upload_to="team/", verbose_name="Фото")),
                ("bio", models.TextField(blank=True, verbose_name="О себе")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Член команды",
                "verbose_name_plural": "Команда ресторана",
                "ordering": ["order", "last_name"],
            },
        ),
    ]
