# Generated by Django 6.0.3 on 2026-03-22 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Настройки", max_length=200, verbose_name="Название"
                    ),
                ),
                (
                    "opening_time",
                    models.TimeField(
                        default=datetime.time(10, 0), verbose_name="Время открытия"
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        default=datetime.time(23, 0), verbose_name="Время закрытия"
                    ),
                ),
                (
                    "min_booking_duration",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Мин. длительность бронирования (часов)"
                    ),
                ),
                (
                    "max_booking_duration",
                    models.PositiveSmallIntegerField(
                        default=5,
                        verbose_name="Макс. длительность бронирования (часов)",
                    ),
                ),
                (
                    "min_advance_booking",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Мин. время до бронирования (часов)"
                    ),
                ),
                (
                    "max_advance_booking",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="Макс. время до бронирования (дней)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активны"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Настройки ресторана",
                "verbose_name_plural": "Настройки ресторана",
            },
        ),
    ]
