# Generated by Django 6.0.3 on 2026-03-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_restaurantsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantsettings",
            name="closes_next_day",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если ресторан работает после полуночи",
                verbose_name="Закрывается на следующий день",
            ),
        ),
    ]
