# Generated by Django 6.0.3 on 2026-03-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_restaurantsettings_closes_next_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantsettings",
            name="address",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Адрес ресторана"
            ),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Широта (latitude)",
            ),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота (longitude)",
            ),
        ),
        migrations.AddField(
            model_name="restaurantsettings",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
        ),
    ]
