# Generated by Django 6.0.3 on 2026-03-22 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_restaurantsettings_address_restaurantsettings_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitecontent",
            options={
                "ordering": ["key"],
                "verbose_name": "Элемент контента",
                "verbose_name_plural": "Элементы контента",
            },
        ),
        migrations.RemoveField(
            model_name="sitecontent",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="sitecontent",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sitecontent",
            name="image_value",
        ),
        migrations.RemoveField(
            model_name="sitecontent",
            name="text_value",
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="content",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="Содержимое"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitecontent",
            name="key",
            field=models.CharField(
                choices=[
                    ("about_history", "История ресторана"),
                    ("about_mission", "Миссия"),
                    ("home_title", "Заголовок главной"),
                    ("home_description", "Описание главной"),
                    ("contacts_title", "Заголовок контактов"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Ключ",
            ),
        ),
        migrations.AlterField(
            model_name="sitecontent",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Заголовок"
            ),
        ),
    ]
