# Generated by Django 6.0.3 on 2026-03-23 14:03

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_sitecontent_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название документа"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Латинские буквы, цифры и дефис (например: offer, privacy-policy)",
                        unique=True,
                        verbose_name="Слаг (для URL)",
                    ),
                ),
                ("content", models.TextField(verbose_name="Текст документа")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ в подвале",
                "verbose_name_plural": "Документы в подвале",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="HeroImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="home_hero",
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Ключ",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Рекомендуемый размер: 1920x800px. Максимальный размер: 2MB. Форматы: JPG, PNG, WEBP",
                        upload_to="hero_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                            core.validators.validate_image_file_size,
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Изображение главного баннера",
                "verbose_name_plural": "Изображения главных баннеров",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("url", models.URLField(verbose_name="Ссылка")),
                (
                    "icon_class",
                    models.CharField(
                        default="bi bi-share",
                        help_text="Класс Bootstrap Icons (например: bi bi-telegram)",
                        max_length=50,
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Ссылка на соцсеть",
                "verbose_name_plural": "Ссылки на соцсети",
                "ordering": ["order", "name"],
            },
        ),
    ]
