# Generated by Django 6.0.3 on 2026-03-23 14:22

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_footerdocument_heroimage_sociallink"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sociallink",
            options={
                "ordering": ["order", "network"],
                "verbose_name": "Ссылка на соцсеть",
                "verbose_name_plural": "Ссылки на соцсети",
            },
        ),
        migrations.RemoveField(
            model_name="sociallink",
            name="icon_class",
        ),
        migrations.RemoveField(
            model_name="sociallink",
            name="name",
        ),
        migrations.AddField(
            model_name="footerdocument",
            name="doc_type",
            field=models.CharField(
                choices=[("text", "Текстовый документ"), ("pdf", "PDF файл")],
                default="text",
                max_length=10,
                verbose_name="Тип документа",
            ),
        ),
        migrations.AddField(
            model_name="footerdocument",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите PDF файл (макс. 5MB). Оставьте пустым, если используете текст.",
                null=True,
                upload_to="documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="PDF файл",
            ),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="custom_name",
            field=models.CharField(
                blank=True,
                help_text='Заполните, если выбрали "Другая соцсеть"',
                max_length=50,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="network",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("vk", "ВКонтакте"),
                    ("odnoklassniki", "Одноклассники"),
                    ("youtube", "YouTube"),
                    ("rutube", "Rutube"),
                    ("zen", "Яндекс.Дзен"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("tiktok", "TikTok"),
                    ("custom", "Другая соцсеть"),
                ],
                default="telegram",
                max_length=30,
                verbose_name="Социальная сеть",
            ),
        ),
        migrations.AlterField(
            model_name="footerdocument",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Заполните для текстового документа",
                verbose_name="Текст документа",
            ),
        ),
        migrations.AlterField(
            model_name="heroimage",
            name="image",
            field=models.ImageField(
                help_text="📐 Рекомендуемый размер: 1920×800px<br>⚖️ Максимальный размер: 2MB<br>📁 Форматы: JPG, PNG, WEBP<br>💡 Совет: используйте фото интерьера с тёплым освещением",
                upload_to="hero_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    core.validators.validate_image_file_size,
                ],
                verbose_name="Изображение",
            ),
        ),
    ]
