# Generated by Django 6.0.3 on 2026-03-21 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Номер столика"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Вместимость (человек)"
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("main", "Основной зал"),
                            ("vip", "VIP-зона"),
                            ("terrace", "Терраса"),
                            ("bar", "Барная стойка"),
                        ],
                        default="main",
                        max_length=20,
                        verbose_name="Зона",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
                "ordering": ["zone", "number"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата бронирования")),
                ("time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "guests_count",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Количество гостей"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("cancelled", "Отменено"),
                            ("completed", "Завершено"),
                            ("no_show", "Клиент не пришёл"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий клиента"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="bookings.table",
                        verbose_name="Столик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-date", "-time"],
                "indexes": [
                    models.Index(
                        fields=["date", "time"], name="bookings_re_date_1b7317_idx"
                    ),
                    models.Index(
                        fields=["status"], name="bookings_re_status_5afb4b_idx"
                    ),
                    models.Index(
                        fields=["user", "status"], name="bookings_re_user_id_02438c_idx"
                    ),
                ],
            },
        ),
    ]
